### ISSUE TITLE
Temperature unit does not follow Homekit config setting

### ISSUE THREAD

**Issue by HoTiCE2** [schemers/homebridge-screenlogic#10]
Hello,
It appears the temperature unit does not follow what we set it in the HomeKit switch but follows the system-wide IOS setting.

I'm in Canada and have the main IOS regional page set by default to Celsius and this is what the pool Heater displays regardless of whether or not if we set it to Celsius or Fahrenheit.

When I switch my iOS completely to Fahrenheit, the Homekit switch for the heat pump does switch to Fahrenheit again regardless of whether the setting is at F or C.

Thanks
GREAT stuff btw

**Comment by schemers** [comment]
Thanks. Are you talking about setting it here?

![IMG_2814](https://user-images.githubusercontent.com/249172/86193908-fa7bcc00-bb01-11ea-9a70-6bbe8612d4e3.png)

That (confusingly) is used to control what the hardware device itself is displaying, not what gets displayed inside of the Home app. For example, if you were using the Nest Homebridge plugin, it would change what gets displayed directly on the Nest hardware. In my case, I'm not doing anything with it.

As you noted, the Home app itself only uses the system-wide iOS setting.
