### ISSUE TITLE
Light color switches not working correctly

### ISSUE THREAD

**Issue by DragonMyAss** [schemers/homebridge-screenlogic#12]
When I turn on any light color switch it will turn on briefly in HomeKit and then turn off as intended per your documentation. The problem is that the light color never changes, but instead my pool pump turns on and turns my valves to activate the spa.

There is no update in the log to show that anything actually happened though.

**Comment by schemers** [comment]
Strange. Seems to be working for me, I observe the (via Screenlogic app) both the spa and pool light turn on (and nothing else).

Do you know what version of the software is running on your protocol adaptor? Mine is:

`5.2 Build 738.0 Rel`

Also, in your Screenlogic app does it show "Intellibrite" under lighting? I believe the command that is sent is for Intellibrite only.

It could also be something special in the way your setup is configured. The [SLLightControlMessage](https://github.com/parnic/node-screenlogic#sllightcontrolmessage) documentation for the module I'm using to talk to the pool has the following comment (as do most if not all of the messages):

> ### Properties
> * controllerId - integer indicating the ID of the controller to send this command to.
>   * Note that while SLControllerConfigMessage includes a controllerId, this ID, in my experience, should always be 0.

I've been using in `0` as the `controllerId` in all the commands I send. The `SLControllerConfigMessage` is returning `100` for my controller id, and IIRC I tried using that value early on and it didn't work, so I ended up using `0` everywhere which is working for all the other commands.

The lighting support is incomplete, [sendLightCommand](https://github.com/parnic/node-screenlogic/blob/master/README.md#sendlightcommandcontrollerid-command) says:

> Note that better/more complete handling of lighting is desired, but I have yet to find all the commands I need to implement to make that happen. This currently sends each command to all lights and there is no ability to send to an individual light. Pull requests adding more functionality here would be most welcome.

I could add some debug messages that will show up if you run Homebridge in debug-mode that might help track down what is going on.

**Comment by schemers** [comment]
I released v2.1.1 with extra debugging. You’ll need to start homebridge with `-D`

You should see something in the log that starts with `[ScreenLogic] controllerConfig ...` and then a bunch of following lines with the debug output for the controller config. That might help debug. 

You don’t need to try and set a light color, hopefully just that output will help.
