### ISSUE TITLE
Homebridge Accessory

### ISSUE THREAD

**Issue by soupflai** [schemers/homebridge-screenlogic#14]
Can the plug-in be added to the "Accessory" tab on the Homebridge interface (where you need to set Homebridge Insecure Mode -i)? Planning to integrate with google assistant if this is possible. Thanks.

**Comment by schemers** [comment]
I'm pretty sure that is at your discretion (running with insecure mode) and there is nothing that plugins need to do to support as Homebridge does all the work.
