### ISSUE TITLE
Hide Circuits

### ISSUE THREAD

**Issue by captainalvarez** [schemers/homebridge-screenlogic#16]
Can not get hide circuits to work. Am I missing something?

 "hidden_circuits": "Aux4, Aux5, Aux6, Aux7, Feature5, Feature6, Feature7, Feature8",

**Comment by schemers** [comment]
Make sure you include a space if there is a space in the name. For example, mine looks like:

```
"hidden_circuits": "Aux 6”,
```

**Comment by captainalvarez** [comment]
Thanks, not sure how i missed that, i figured i was missing something obvious.
