### ISSUE TITLE
Error with latest version

### ISSUE THREAD

**Issue by DragonMyAss** [schemers/homebridge-screenlogic#8]
Just want start out by thanking you for making this plugin! Absolutely awesome!! I am getting this error since updating to the latest version (2.0.1):

 “ The requested platform "ScreenLogic" was not registered by any plugin.
6/24/2020, 2:37:28 PM Your config.json is requesting the platform "ScreenLogic" which has not been published by any installed plugins.”

Any ideas what I might be doing wrong?

Also, any idea if there is a way to add the ability control a variable speed pump via rpm and flow control?

Thanks!

**Comment by DragonMyAss** [comment]
This is what my config.json looks like

"platforms": [
        {
            "platform": "ScreenLogic",
            "plugin_map": {
                "plugin_name": "homebridge-screenlogic"
            },
            "hidePoolTemperatureSensor": true,
            "hideSpaTemperatureSensor": true,
            "hideAirTemperatureSensor": false,
            "hidePoolThermostat": false,
            "hideSpaThermostat": false,
            "statusPollingSeconds": 60,
            "hidden_circuits": "Aux 6,Aux 7,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,AuxEx,USERNAME-01,USERNAME-02,USERNAME-03, USERNAME-04, USERNAME-05, USERNAME-06, USERNAME-07, USERNAME-08, USERNAME-09"
        }
    ]

**Comment by schemers** [comment]
Thanks. I think that config looks reasonable. 

You might have to upgrade Homebridge and/or Node, if you aren't at these versions:

``` 
"engines": {
    "node": ">=10.17.0",
    "homebridge": ">=1.1.1"
  },
```

I updated version 2.0 to use the latest version of Homebridge and rewrote it in Typescript so I could make it more reliable and use the dynamic platform apis (which prevents all the accessories from disappearing if pentair protocol gateway is unavailable when the server starts).

I was assuming that the plugin wouldn't update unless those versions are met, since I put that in the `package.json` file.

I think the [API](https://github.com/parnic/node-screenlogic#slsetpumpflow) I'm using supports setting RPMs, I'm not sure how well it maps to HomeKit though.

**Comment by DragonMyAss** [comment]
I am using Node Version 12.14.1, but I am running HOOBS 3.2.6. HOOBS probably isn’t support Homebridge version 1.1.1

**Comment by schemers** [comment]
ah. If you can't upgrade homebridge version right now, you can reinstall the previous version using nom. Something like:

```
(login to wherever homebridge is running)
npm install homebridge-screenlogic@v1.4.3 -g
```

I was running Hoobs as well, but it didn't seem worth the hassle once Homebridge 1.0 was released.

I ended up switching to this [homebridge-raspbian-image](https://github.com/homebridge/homebridge-raspbian-image) when I saw it announced.

**Comment by schemers** [comment]
I know that the Ring plugin required Homebridge 1.0, and it still was working under Hoobs:

https://github.com/dgreif/ring/releases/tag/v8.0.0

there might be something I can do it to make it work, I can try and take a look this weekend if I get a chance

**Comment by schemers** [comment]
I just got a pull request from someone with a simple change that looks like it might enable hoobs support, so stand by

**Comment by schemers** [comment]
I pushed a new version (2.0.2) which should hopefully work with Hoobs again. Might take a little while to show up in your updates.

**Comment by BobbySlope** [comment]
@schemers yes that was our dev. thanks for updating. we like to keep in touch with you, please write us an email at plugindev@hoobs.org. we can also see go get your plugin certified.

regards Bobby from hoobs.org

**Comment by DragonMyAss** [comment]
All appears to be working again. Thanks for taking the time to update!

**Comment by schemers** [comment]
glad to hear! I'll close this and you can open another one for pump control if you'd like. That would take some time to explore as well as figure out if there is a good way to repent it it in HomeKit.
